---
title: "Linear Discriminant Analysis - One versus all"
author: "Solène Pety"
date: "22/04/2021"
output:
  html_document:
    toc: yes
    toc_float: true
    code_folding: hide
    df_print: paged
---

```{r init,message=FALSE,warning=FALSE,results="asis"}
library(FactoMineR)
library(factoextra)
library("corrplot")
library(ggsci)
library(plotly)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(pander)
library(knitr)
library(vegan)
library(MASS)
library(RColorBrewer) #Palettes
library(prodlim)
library(scales)
library(ggplotify)
library(kableExtra)
library(ComplexHeatmap)
library(cowplot)
library(viridis)
library(here)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE,results="asis",root.dir =here())
```


# **Détails échantillons projetés**  
```{r sample,cache=TRUE}

abiotic=c("DROUGHT","GAMMA","HEAVY.METAL","NITROGEN","OTHER-ABIOTIC","OXYDATIVE.STRESS","SALT","TEMPERATURE","UV")

files=c("GOSLIM_circadian_rythm.txt",
        "GOSLIM_photo.txt",
        "DEGDROUGHT.txt",
        "DEGGAMMA.txt",
        "DEGOTHER.ABIOTIC.txt",
        "DEGSALT.txt")

name=c("Circadian rythm",
       "Photosynthesis",
       "Drought",
       "Gamma",
       "Other abiotic",
       "Salt")

raw_data=read.table(here("data","GEM2Net","GEM2Net_data.txt"),header=TRUE,sep='\t',check.names = FALSE)
raw_abiotic=raw_data[raw_data[,2] %in% abiotic, ]

#######################Création échantillons
################Echantillon 1
set.seed(123)
  sample1=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample1[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table1=raw_abiotic[sample1,1:3]
colnames(sample_table1)<-c("Project ID","Stress","Swap ID")
rownames(sample_table1)<-c(1:9)
 
 
################Echantillon 2
 set.seed(1)
  sample2=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample2[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table2=raw_abiotic[sample2,1:3]
colnames(sample_table2)<-c("Project ID","Stress","Swap ID")
rownames(sample_table2)<-c(1:9)


################Echantillon 3
 set.seed(3)
  sample3=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample3[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table3=raw_abiotic[sample3,1:3]
colnames(sample_table3)<-c("Project ID","Stress","Swap ID")
rownames(sample_table3)<-c(1:9)


################Echantillon 4
 set.seed(4)
  sample4=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample4[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table4=raw_abiotic[sample4,1:3]
colnames(sample_table4)<-c("Project ID","Stress","Swap ID")
rownames(sample_table4)<-c(1:9)
 
################Echantillon 5
 set.seed(5)
  sample5=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample5[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table5=raw_abiotic[sample5,1:3]
colnames(sample_table5)<-c("Project ID","Stress","Swap ID")
rownames(sample_table5)<-c(1:9)

 
################Echantillon 6
 set.seed(6)
  sample6=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample6[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table6=raw_abiotic[sample6,1:3]
colnames(sample_table6)<-c("Project ID","Stress","Swap ID")
rownames(sample_table6)<-c(1:9)
 
################Echantillon 7
 set.seed(7)
  sample7=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample7[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table7=raw_abiotic[sample7,1:3]
colnames(sample_table7)<-c("Project ID","Stress","Swap ID")
rownames(sample_table7)<-c(1:9)
 
################Echantillon 8
 set.seed(8)
  sample8=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample8[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table8=raw_abiotic[sample8,1:3]
colnames(sample_table8)<-c("Project ID","Stress","Swap ID")
rownames(sample_table8)<-c(1:9)

 
################Echantillon 9
 set.seed(9)
  sample9=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample9[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table9=raw_abiotic[sample9,1:3]
colnames(sample_table9)<-c("Project ID","Stress","Swap ID")
rownames(sample_table9)<-c(1:9)

 
################Echantillon 10
 set.seed(10)
  sample10=c()
  for(i in 1:9){
    data_short=raw_abiotic[which(raw_abiotic[,2]==abiotic[i]),]
    sample10[i]=row.names(data_short[sample(1:nrow(data_short), 1), ])
  }

sample_table10=raw_abiotic[sample10,1:3]
colnames(sample_table10)<-c("Project ID","Stress","Swap ID")
rownames(sample_table10)<-c(1:9)
   
 samples=list(sample1,sample2,sample3,sample4,sample5,sample6,sample7,sample8,sample9,sample10)

 knitr::kables(
   list(
     knitr::kable(sample_table1,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray"),
     knitr::kable(sample_table2,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray"),
     knitr::kable(sample_table3,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray")
   ),
   caption="Summary des 10 sets d\'échantillons à prédire")
 
 knitr::kables(
   list(
     knitr::kable(sample_table4,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray"),
     knitr::kable(sample_table5,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray"),
     knitr::kable(sample_table6,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray")
   ))
 
 knitr::kables(
   list(
     knitr::kable(sample_table7,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray"),
     knitr::kable(sample_table8,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray"),
     knitr::kable(sample_table9,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray"),
     knitr::kable(sample_table10,align='c')%>%kable_styling("striped")%>%column_spec(column = 1,border_left = "2px solid gray",border_right = FALSE)%>%column_spec(column = 3,border_left = FALSE,border_right = "2px solid gray")
   ))
  
```

# **Prédiction One-vs-all**

```{r predict,cache=TRUE}

matrix=matrix(0,nrow=1,ncol=9)
matrix_prob=matrix(0,nrow=length(files),ncol=9)

for(i in 1:length(files)){
  
table_prob=data.frame(rep(0,9),rep(0,9),rep(0,9),rep(0,9),rep(0,9),rep(0,9),rep(0,9),rep(0,9),rep(0,9))
match=c(0,0,0,0,0,0,0,0,0)
  
   cat("\n")
  
  data=read.table(here("data","subsets",files[i]),header=TRUE,sep='\t',check.names = FALSE)
    
  pander::pandoc.header(paste0(" **", name[i] ," (",dim(data)[2]-3," gènes)**\n"), level = 2)  
  
   cat("\n")
    for(j in 1:length(samples)){
  #récupération échantillons abiotiques seulement
  data_abiotic=data[data[,2] %in% abiotic, ]
  #dataframe échantillons à projeter + supprimer rows correspondantes
  set_test=data_abiotic[unlist(samples[j]),]
  data_abiotic <- data_abiotic[- which(rownames(data_abiotic) %in% unlist(samples[j])), ] 
  rownames(set_test)<-c(1:9)
  
  logset_test=set_test
  logdata_abiotic=data_abiotic
     
  prob=matrix(0,nrow=9,ncol=9)
  for(k in 1:length(abiotic)){
    logdata_abiotic$vec <- ifelse(data_abiotic$vec==abiotic[k],1,0)
    logset_test$vec <- ifelse(set_test$vec==abiotic[k],1,0)
    logits <- lda(vec~.,data=logdata_abiotic)
    pred <-  predict(logits, logset_test,type="response")
    prob[k,]=round(pred[["posterior"]][,2],4)
    }
  
  table_prob=table_prob+as.data.frame(prob)
  
  vec=c()
  for(l in 1:9){
    pos=order(prob[l,],decreasing=TRUE)[1]
    vec[l]=abiotic[pos]
    }
  match<-match+(vec == abiotic)
  }
   
     pander::pandoc.header(paste0(" **Matrice probabilitées**\n"), level = 3)
     cat("\n")
       
  table_prob=table_prob/length(samples)
  rownames(table_prob)=colnames(table_prob)=abiotic
  print(knitr::kable(table_prob,digits=4,align = 'c')%>%add_header_above(c(" "=1,"Catégories de stress" = 9))%>%kable_styling("striped"))

  ######################################Matrice proba par gene set############
matrix_prob[i,]=c(table_prob[1,1],table_prob[2,2],table_prob[3,3],
                     table_prob[4,4],table_prob[5,5],table_prob[6,6],
                     table_prob[7,7],table_prob[8,8],table_prob[9,9])
###################################################
  
  ##################################### ggbarplot#######################
    pander::pandoc.header(paste0(" **Stacked Barplot**\n"), level = 3)
     cat("\n")
     
    table_long=table_prob%>%pivot_longer(
                        cols=c(1:9),
                       names_to = "Cat",
                       values_to = "Prob") 
     x=rep(abiotic, each=9)
     table_long=cbind(x,table_long)
     
   print(ggplot(table_long, aes(fill=Cat, y=Prob, x=x)) + 
  geom_bar(position='stack', stat='identity') +
    theme(axis.text.x = element_text(angle=45)) +
     xlab("Catégorie de stress") +
     ylab("Probabilité d'appartenance")+
     scale_fill_manual(values = c("darkred","darkorange2","gold2",
                                  "olivedrab2","forestgreen","cadetblue1",
                                  "dodgerblue2","darkorchid3","darkslategray"))) 
###################################################
   
  matrix=rbind(matrix,match)
}

matrix=matrix[-1,]
matrix=as.data.frame(apply(matrix, 2, as.numeric))

   cat("\n")
  pander::pandoc.header(paste0(" **Tableau proportion échantillons bien classés**\n"), level = 2)
  
matrix=matrix/10
matrix=rbind(abiotic,matrix)
rownames(matrix)=c("Stress théorique","Circadian rythm","Photosynthesis","Drought",
       "Gamma","Other abiotic","Salt")
colnames(matrix)=c("Sample 1","Sample 2","Sample 3","Sample 4","Sample 5","Sample 6","Sample 7","Sample 8","Sample 9")

   print(knitr::kable(matrix,align='c')%>%kable_styling("striped")%>%column_spec(1,bold=TRUE))
   
```

```{r heatmap}
############################Heatmap########################
 cat("\n")
  pander::pandoc.header(paste0(" **Heatmap Gene set **\n"), level = 2)

  rownames(matrix_prob) <- c("Circadian rythm set","Photosynthesis set","Drought set",
       "Gamma set","Other abiotic set","Salt set")
  colnames(matrix_prob) <- abiotic
  Heatmap(matrix_prob, name = "Probabilité",col=viridis(30))
```

```{r end,collapse = TRUE,results='hold'}
sessionInfo()
```
