---
title: "Stress abiotiques"
author: "Solène Pety"
date: "07/04/2021"
output:
  html_document:
    toc: yes
    toc_float: true
    code_folding: hide
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE,results="asis",root.dir = "~/M1_BIMS/Stage/Rstudio/.Rmd_html/")
```

```{r init}
library(FactoMineR)
library(factoextra)
library("corrplot")
library(ggsci)
library(plotly)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ComplexUpset)
library(pander)
library(knitr)
library(discoveR)
library(ade4)
library(adegraphics)
library(vegan)
library(MASS)
library(ComplexUpset)
library(RColorBrewer)
library(ggplotify)
```
  
# **Rappel : ACP globale **  

Le but de ce fichier est de tester la classification des **stress de *GEM2NET* **. Ecarter les valeurs fragiles. Améliorer la classification en tentant d'établir des **sous-catégories** de stress.  
   
Le **poids des projets** est aussi à étudier dans une deuxième partie.

```{r ACP_globale}
setwd("../docs_txt/")

data=read.table('table_data.txt',header=TRUE,sep='\t')

abiotic=c("DROUGHT","GAMMA","HEAVY.METAL","NITROGEN","OTHER-ABIOTIC","OXYDATIVE.STRESS","SALT","TEMPERATURE","UV")

data_abiotic=data[data[,2] %in% abiotic, ]
row.names(data_abiotic) <- data_abiotic$Swap_ID
res1=PCA(data_abiotic[,c(-1,-3)],scale.unit=FALSE,graph=FALSE,quali.sup=1) 
fviz_pca_ind(res1,
             repel=TRUE,
             habillage = 1, # color by groups
             addEllipses = FALSE, # Concentration ellipses
            # select.ind = list(cos2 = 0.2),
             title="All genes \n stress abiotiques"
      )

fviz_pca_ind(res1,
             repel=TRUE,
             habillage = 1, # color by groups
             addEllipses = FALSE, # Concentration ellipses
             select.ind = list(cos2 = 0.2),
             title="All genes \n stress abiotiques (cos2 > 0.2)"
      )
```

# **ACP par project ID**
```{r ACP_ID}
setwd("../docs_txt/")

files=c("circadian_rythm.txt","photo.txt","DEGDROUGHT.txt","DEGGAMMA.txt","DEGHEAVY.METAL.txt","DEGNITROGEN.txt","DEGOTHER.ABIOTIC.txt","DEGOXYDATIVE.STRESS.txt","DEGSALT.txt","DEGTEMPERATURE.txt","DEGUV.txt")

name=c("Circadian rythm","Photosynthesis","Drought","Gamma","Heavy Metal","Nitrogen","Other abiotic","Oxydative stress","Salt","Temperature","UV")

for(i in 1:length(files)){
#Chargement Gene set 
  data=read.table(files[i],header=TRUE,sep='\t',check.names = FALSE)

  data_abiotic=data[data[,2] %in% abiotic, ]
  names=data_abiotic$vec2
  rownames(data_abiotic) = make.names(names, unique=TRUE)

  cat("\n")
  pander::pandoc.header(paste0("**Gene set : ",name[i]," (",dim(data)[2]-3," gènes)**\n"), level = 2)

#--------------------------------------------------------------------------------------------------#
                                              # ACP gene set, project ID
#--------------------------------------------------------------------------------------------------#  
    cat("\n")
    pander::pandoc.header(paste0("**ACP**\n"), level = 3)
    
    res1=PCA(data_abiotic[,c(-1,-3)],scale.unit=FALSE,graph=FALSE,quali.sup=1) 
    g1<-fviz_pca_ind(res1,
             repel=TRUE,
             habillage = 1, # color by groups
             addEllipses = FALSE, # Concentration ellipses
             title="Coloration par project ID"
      )
      
      q <- ggplot_build(g1)
      q[["data"]][[3]][["label"]] <- names
      q <- ggplot_gtable(q)
      print(as.ggplot(q)) ## Change row names after the fact

#--------------------------------------------------------------------------------------------------#
                                                # kmeans
#--------------------------------------------------------------------------------------------------#        
      
      cat("\n")
      pander::pandoc.header(paste0("**kmeans**\n"), level = 3)     
      
      data_abiotic=data[data[,2] %in% abiotic, ]
      
      
      cat("\n")
      pander::pandoc.header(paste0("**Screeplot**\n"), level = 4) 
      
      inertie.expl=c()
      for(i in 1:15){
        S=kmeans(data_abiotic[,c(-1,-2,-3)],centers=i)
        inertie.expl[i] <-S$tot.withinss
      }
      plot(1:15,inertie.expl,type="b",xlab="Nb clusters",ylab="Within cluster sum of squares")
      
      cat("\n")
      pander::pandoc.header(paste0("**7 clusters**\n"), level = 4)     
    
      S=kmeans(data_abiotic[,c(-1,-2,-3)],centers=7)
      data_abiotic=cbind(S$cluster,data_abiotic)

      res1=PCA(data_abiotic[,c(-2,-4,-3)],scale.unit=FALSE,graph=FALSE,quali.sup=1)

       g1<-fviz_pca_ind(res1,
             repel=TRUE,
             habillage = 1, # color by groups
             addEllipses = FALSE, # Concentration ellipses
             title=paste("Coloration par 7 clusters")
      )
       
      q <- ggplot_build(g1)
      q[["data"]][[3]][["label"]] <- names
      q <- ggplot_gtable(q)
      print(as.ggplot(q)) ## Change row names after the fact
       
       cat("\n")

      pander::pandoc.header(paste0("**Répartition stress par cluster**\n"), level = 4) 
      #colonne 1 = cluster
      #colonne 2+1 = stress
      
      table=matrix(0,nrow=7,ncol=9,dimnames=list(c("Cluster 1", "Cluster 2", "Cluster 3",
                                                "Cluster 4", "Cluster 5", "Cluster 6", "Cluster 7"),
                                                abiotic))
      for(j in 1:7){
        for(i in 1:9){
          cat("\n")
          table[j,i]=dim(data_abiotic[which(data_abiotic[,1]==j & data_abiotic[,3]==abiotic[i]),])[1]
        }
      }
      
      Total1=apply(table,1,sum)
      Total2=apply(table,2,sum)
      Total2[10]=sum(Total1)
      table=cbind(table,Total1)
      table=rbind(table,Total2)
      
       print(knitr::kable(table, format = "markdown"))
}
```




