---
title: "Predictions"
author: "Solène Pety"
date: "15/04/2021"
output:
  html_document:
    toc: yes
    toc_float: true
    code_folding: hide
    df_print: paged
---
```{r init,message=FALSE,warning=FALSE,results="asis"}
library(FactoMineR)
library(factoextra)
library("corrplot")
library(ggsci)
library(plotly)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(pander)
library(knitr)
library(vegan)
library(MASS)
library(RColorBrewer) #Palettes
library(prodlim)
library(ggplotify)
library(here)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE,results="asis",root.dir=here())
```

L'objectif est ici de tester la prédiction à partir du modèle de classification que nous avons pu déterminer.  

C'est le fichier **GOSLIM_circadian_rythm.txt** qui va être utilisé. C'est le plus petit Gene Set des GO SLIM, sans doute un des plus précis.  

# **ACP Gene Set entier (57 gènes)**  
```{r files}

abiotic=c("DROUGHT","GAMMA","HEAVY.METAL","NITROGEN","OTHER-ABIOTIC","OXYDATIVE.STRESS","SALT","TEMPERATURE","UV")

#Chargement Gene set 
data=read.table(here("data","subsets","GOSLIM_circadian_rythm.txt"),header=TRUE,sep='\t',check.names = FALSE)

data_abiotic=data[data[,2] %in% abiotic, ]
names=data_abiotic$vec2
res1=PCA(data_abiotic[,c(-1,-3)],graph=FALSE,quali.sup=1)

g1<-fviz_pca_ind(res1,
             repel=TRUE,
             habillage = 1, # color by groups
             addEllipses = FALSE, # Concentration ellipses
             title="Coloration par project ID\n Scaling=TRUE"
 )
      
q <- ggplot_build(g1)
q[["data"]][[3]][["label"]] <- names
q <- ggplot_gtable(q)
print(as.ggplot(q)) ## Change row names after the fact
```

# **Projection factomineR**  

```{r pred}
  liste=sample(c(1:224),10)

  set_test=data_abiotic[liste,]
  rownames(set_test)<-c(1:10)

  set_stress=set_test$vec
  set_id=set_test$vec2
  data_abiotic=data_abiotic[-liste,]
  project_id=data_abiotic$vec2
  swap=data_abiotic$Swap_ID
  stress=data_abiotic$vec
 
   cat("\n")
   pander::pandoc.header(paste0("**ACP sans projection**\n"), level = 2)      
  
   res1=PCA(data_abiotic[,c(-1,-3)],graph=FALSE,quali.sup=1)

      g1<-fviz_pca_ind(res1,
             repel=TRUE,
             habillage = 1, # color by groups
             addEllipses = FALSE, # Concentration ellipses
             title="Coloration par project ID \n 214 Observations | scaling=TRUE",
             show.legend=FALSE
      )
      
      q <- ggplot_build(g1)
      q[["data"]][[3]][["label"]] <- project_id
      q <- ggplot_gtable(q)
      print(as.ggplot(q)) ## Change row names after the fact
      
  cat("\n")    
  pander::pandoc.header(paste0("**Détails échantillons projetés**\n"), level = 2)          
 
  coord_predict=predict.PCA(res1,set_test) 
 coord=coord_predict$coord[,c(1:2)]
 coord=as.data.frame(coord)
 coord=cbind(set_stress,set_id,coord)
 colnames(coord)<-c("Stress","Project_ID","Dim1","Dim2")
 coord
 
 
 #Ajout des données sur le graph
  pander::pandoc.header(paste0("**ACP + projection**\n"), level = 2)     
 p=fviz_add(g1,coord[,c(3,4)],col="red")
 p[["labels"]][["title"]]<-"Coloration par project ID \n Projection des points en rouge (n° ligne)"

 
 q2 <- ggplot_build(p)
      q2[["data"]][[3]][["label"]] <- project_id
      q2 <- ggplot_gtable(q2)
      print(as.ggplot(q2)) ## Change row names after the fact
      


```