---
title: "Analyse différentielle"
author: "Solène Pety"
date: "02/04/2021"
output:
  html_document:
    toc: yes
    toc_float: true
    code_folding: hide
    df_print: paged
---

```{r init,message=FALSE,warning=FALSE,results="asis"}
library(FactoMineR)
library(factoextra)
library("corrplot")
library(ggsci)
library(plotly)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(ComplexUpset)
library(pander)
library(knitr)
library(discoveR)
library(ade4)
library(adegraphics)
library(vegan)
library(MASS)
library(ComplexUpset)
library(RColorBrewer)
library(cowplot)
library(here)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE,results="asis",root.dir=here())
```


**Dans ce document, nous visualisons à l'aide d'ACP les résultats de l'analyse différentielle pour les listes de gènes DEGs sans UV puis sans NECROTROPHIC BACTERIA pour les stress respectivement abiotiques et biotiques.**  

# **Stress abiotiques**  
```{r ACP1}

data=read.table(here("data","subsets","DEG_withoutUV.txt"),header=TRUE,sep='\t')

abiotic=c("DROUGHT","GAMMA","HEAVY.METAL","NITROGEN","OTHER-ABIOTIC","OXYDATIVE.STRESS","SALT","TEMPERATURE","UV")

data_abiotic=data[data[,2] %in% abiotic, ]
row.names(data_abiotic) <- data_abiotic$Swap_ID

res1=PCA(data_abiotic[,c(-1,-3)],scale.unit=FALSE,graph=FALSE,quali.sup=1)
  fic.pca1<-dudi.pca(data_abiotic[,c(-1,-2,-3)],center=FALSE,scale=FALSE,scannf=FALSE)
  fic.bca1<-bca(fic.pca1,fac=as.factor(data_abiotic$vec),scannf=FALSE)
  fic.tst<-randtest(fic.bca1)
  
  cat("\n")  
  pander::pandoc.header(paste0("**ACP**\n"), level = 2)
  
  
      g1<-fviz_pca_ind(res1,
             repel=TRUE,
             habillage = 1, # color by groups
             addEllipses = TRUE, # Concentration ellipses
             palette="Set1"
      )
      print(g1)
      
      
      cat("\n")
      pander::pandoc.header(paste0("*Inertie*\n"), level = 3)
      print(fviz_screeplot(res1, addlabels = TRUE, ylim = c(0, 50)))
      
      
      cat("\n")
      pander::pandoc.header(paste0("*Contribution*\n"), level =3)
      
      cat("\n")
      pander::pandoc.header(paste0("**Individus**\n"), level =4)
      print((fviz_contrib(res1, choice = "ind", axes = 1, top = 10)
        +
      fviz_contrib(res1, choice = "ind", axes = 2, top = 10)))
      
      cat("\n")
      pander::pandoc.header(paste0("**Variables**\n"), level =4)
      print((fviz_contrib(res1, choice = "var", axes = 1, top = 10)
        +
      fviz_contrib(res1, choice = "var", axes = 2, top = 10)))

      
      cat("\n")
      pander::pandoc.header(paste0("**BCA**\n"), level = 2)
      
      cat("\n")
      pander::pandoc.header(paste0("*Toutes positions*\n"), level = 3)
      
      .z<-paste("BCA sur position \n ratio= ",round(fic.bca1$ratio,2)," pval= ",signif(fic.tst$pvalue,digits=2))

      s.class(fic.bca1$ls,
              fac=as.factor(data_abiotic$vec),
              col=brewer.pal(n=9,name="Set1"),
              psub=list(text=.z,cex=1,position="topleft"),
              plabels.cex=0,
              key.cex=0.8,
              key.text.cex=0.8)

      
      cat("\n")
      pander::pandoc.header(paste0("*Par position*\n"), level = 3)
      
      plotlist=list()

      for(j in 1:9){
        s.class(fic.bca1$ls,
                fac=as.factor(data_abiotic$vec),
                psub=list(text=paste("BCA \n", abiotic[j]),cex=1,position="topleft"),
                plabels.cex=0,
                key.cex=0.4,
                key.text.cex=0.4,
                col=c(rep(grey(0.95),j-1),brewer.pal(n=9,name="Set1")[j],rep(grey(0.95),9-j)),
                plot=FALSE,
                chullSize=0,
                ellipseSize=0)->plotlist[j]
      }

      ADEgS(plotlist,layout=c(3,3))
```
  
# **Stress biotiques**  
 
```{r ACP2,results='asis'}

  data=read.table(here("data","subsets","DEGwithoutNECRO.txt"),header=TRUE,sep='\t')
  
  biotic=c("BIOTROPHIC.BACTERIA","FUNGI","NECROTROPHIC.BACTERIA","NEMATODES","OOMYCETE","OTHER-BIOTIC","RHODOCOCCUS","STIFENIA","VIRUS")

  data_biotic=data[data[,2] %in% biotic, ]
  row.names(data_biotic) <- data_biotic$Swap_ID
  res1=PCA(data_biotic[,c(-1,-3)],scale.unit=FALSE,graph=FALSE,quali.sup=1)
  fic.pca1<-dudi.pca(data_biotic[,c(-1,-2,-3)],center=FALSE,scale=FALSE,scannf=FALSE)
  fic.bca1<-bca(fic.pca1,fac=as.factor(data_biotic$vec),scannf=FALSE)
  fic.tst<-randtest(fic.bca1)
  
  cat("\n")
  pander::pandoc.header(paste0("**ACP**\n"), level = 2)
      
  g1<-fviz_pca_ind(res1,
             repel=TRUE,
             habillage = 1, # color by groups
             addEllipses = TRUE, # Concentration ellipses
             palette="Set1"
      )
  print(g1)
  
  
  cat("\n")
  pander::pandoc.header(paste0("*Inertie*\n"), level = 3)
  print(fviz_screeplot(res1, addlabels = TRUE, ylim = c(0, 50)))
     
   
  cat("\n")
  pander::pandoc.header(paste0("*Contribution*\n"), level =3)
      
  cat("\n")
  pander::pandoc.header(paste0("**Individus**\n"), level =4)
  print((fviz_contrib(res1, choice = "ind", axes = 1, top = 10)
        +
  fviz_contrib(res1, choice = "ind", axes = 2, top = 10)))
  
  cat("\n")
  pander::pandoc.header(paste0("**Variables**\n"), level =4)
  print((fviz_contrib(res1, choice = "var", axes = 1, top = 10)
        +
  fviz_contrib(res1, choice = "var", axes = 2, top = 10)))
  
  cat("\n")
  pander::pandoc.header(paste0("**BCA**\n"), level = 2)
  
  cat("\n")
  pander::pandoc.header(paste0("*Toutes positions*\n"), level = 3)
  
      
  .z<-paste("BCA sur position \n ratio= ",round(fic.bca1$ratio,2)," pval= ",signif(fic.tst$pvalue,digits=2))

  s.class(fic.bca1$ls,
          fac=as.factor(data_biotic$vec),
          col=rainbow(9),
          psub=list(text=.z,cex=1,position="topleft"),
          plabels.cex=0,
          key.cex=0.8,
          key.text.cex=0.8)

  cat("\n")
  pander::pandoc.header(paste0("*Par position*\n"), level = 3)
      
  plotlist=list()
  for(j in 1:9){
    s.class(fic.bca1$ls,
            fac=as.factor(data_biotic$vec),
            psub=list(text=paste("BCA \n", biotic[j]),cex=1,position="topleft"),
            plabels.cex=0,
            key.cex=0.4,
            key.text.cex=0.4,
            col=c(rep(grey(0.95),j-1),brewer.pal(n=9,name="Set1")[j],rep(grey(0.95),9-j)),
            plot=FALSE,
            chullSize=0,
            ellipseSize=0)->plotlist[j]
  }

  ADEgS(plotlist,layout=c(3,3))
```
  
